INSERT INTO persona.games (game_name, description, protagonist, color, image_link)
VALUES ('Persona 1', 
'Persona 1 summary: Set in 1996, Megami Ibunroku Persona centers around the protagonist and his classmates at St. Hermelin High School in Mikage-cho (Lunarvale in Revelations: Persona). Hidehiko Uesugi talks all of his friends into playing a game called "Persona", which is played much like the ritual game "Bloody Mary". While playing, the students lose consciousness and meet Philemon, who gives them the ability to summon reflections of their personalities, which are known as Personas.',
'The Protagonist of the first Persona game is a student of St.Hermelin High School. He is referred to as the "pierced boy" in the Japanese version of Persona 1, and the "Boy with Earring" in Persona 2: Eternal Punishment. In the original English release, Revelations Persona, he had no piercings.',
'Purple',
'https://i.imgur.com/bNHLMLX.png'),
('Persona 2', 
'Persona 2 Innocent Sin: Persona 2: Innocent Sin begins three years after the events of the first Persona, in 1999. The location is Sumaru City, a large fictional metropolitan area set in modern day Japan. Sumaru City becomes cursed after events during the beginning of the game that cause any rumor that spreads enough to become true. Persona 2 Eternal Punishment: Eternal Punishment focuses on protagonist Maya Amano. Eternal Punishment takes place on "the other side" from Innocent Sin. Rumors are spread about how if you call your cell phone, the JOKER will come and kill whoever you ask it to. Maya Amano is sent to write a story about the JOKER, when she meets him in person. Philemon grants Maya and her friends the ability to summon Personas, an ability that they use to hunt JOKER.',
'Tatsuya is the protagonist of Persona 2: Innocent Sin, and the secondary protagonist of Persona 2: Eternal Punishment. His default name is "Tatsuya Suou", the player can change it at anytime. Maya Amano is the progtagonist of Persona 2 Eternal Punishment. She is also the secondary protagonist in Persona 2: Innocent Sin.',
'Red',
'https://i.imgur.com/9RQ0G1P.jpg' ) ,
('Persona 3', 
'Persona 3 follows a group of high school students trying to cope with, understand and accept death in a world surrounded by it, as well as find their own reasons for living. They form a group called SEES in order to investigate the Dark Hour, a mysterious time period between one day and the next that few people are aware of. During the Dark Hour, SEES explores Tartarus, a large tower containing Shadows, creatures that feed on the minds of humans. To fight the Shadows, each member of SEES is able to summon a Persona, a manifestation of their inner self.',
'The female protagonist of Persona 3 Portable, known as Kotone Shiomi in the stage play and by default in the 2023 re-release of the game, is a transfer student enrolling in Gekkoukan High School on Tatsumi Port Island. She is an orphan whose parents died on the Moonlight Bridge in their car during a fatal incident a decade prior to the game.
She is the female counterpart of Makoto Yuki: she is designed to present a fresh perspective for veteran players of the Persona 3 series.Because the rest of the Persona series takes direct reference to the original interpretation of the game involving the male protagonist, her story is effectively non-canonical and takes place in a separate timeline.',
'Blue',
'https://i.imgur.com/KX2JeSl.jpg' ),
('Persona 4', 
'Persona 4 follows a group of high school students dealing with a mysterious TV channel dedicated to distorting and exaggerating the truth of who they are and their identities. A string of bizarre murders related to the TV channel begins shaking their once peaceful town. They explore the mysterious world inside the TV and perform rescue missions in order to save its victims from death. Only by looking past what is on the screen, finding and evaluating the truth among a myriad of lies can they hope to find the serial killer and save their town.',
'The protagonist of Persona 4, canonically known as Yu Narukami starting with its use in Persona 4 Arena, is a transfer student at Yasogami High School, and resides for a year at Inaba, a rural town',
'Yellow',
'https://i.imgur.com/yV6Nvfl.jpg' ),
('Persona 5', 
'Persona 5 is a fantasy based on reality which follows a group of troubled high school students: the protagonist and a collection of compatriots he meets along the way. These disturbed and troubled teenagers gradually realize that they are living in a toxic and dangerous world resembling a prison full of slavery, oppression and injustice, ruled by corrupted and twisted adults. They cannot live with the system and can''t live without it, and simply existing means they are at risk of being doomed and condemned to a life of slavery.',
'The protagonist of Persona 5, known as Ren Amamiya in most appearances (including by default in the 2022 re-release of Persona 5 Royal), is a second-year transfer student at Shujin Academy, being placed there to continue his academics due to his ongoing probation resulting from being falsely framed for assault',
'Royal Red',
'https://i.imgur.com/3E4fbdM.jpg' ),
('Persona 5 Strikers', 
'Months after the events of Persona 5, the Phantom Thieves of Hearts plan to go on summer vacation as the protagonist and Morgana reunite with them upon their return to Tokyo. Despite their celebration, during that night, Lavenza appears as the Velvet Rooms sole resident and warns the protagonist of a "potential calamity" that may "consume the world whose heart he strove so greatly to change."',
'The protagonist of Persona 5, known as Ren Amamiya in most appearances (including by default in the 2022 re-release of Persona 5 Royal), is a second-year transfer student at Shujin Academy, being placed there to continue his academics due to his ongoing probation resulting from being falsely framed for assault',
'Royal Red',
'https://i.imgur.com/SspOkVa.jpg' ) 